### ISSUE TITLE
Accessing through SSL

### ISSUE THREAD

**Issue by cdancy** [SubhakarKotta/azure-aks-vagrant-ubuntu#5]
Trying to follow [THIS](https://github.com/SubhakarKotta/azure-aks-vagrant-ubuntu#access-kubernetes-dashboard) did not work. The ssh command failed and didn't prompt for a password (was it supposed to?) as it looks like it expected a key. Maybe that was from the previous steps?

**Comment by s-u-b-h-a-k-a-r** [comment]
Hi @cdancy what is the error ur getting. can we delete the entries in /users/hosts/ssh?

**Comment by cdancy** [comment]
@SubhakarKotta pinged you on webex but maybe you didn't see it. What do you think about combining all of your various `vagrant-ubuntu` repos into a single repo with folders for each? Then we can move than under the `pegasystems` project here on github and folks can clone a single project and `cd` into whichever folder they want to use.

**Comment by s-u-b-h-a-k-a-r** [comment]
@cdancy I am on leave this week and will be back to office on Monday and we can combine all of them into one folder if we are moving under pegasystems

**Comment by cdancy** [comment]
@SubhakarKotta sounds good. I'm actually going to combine them here, create a project with all of them, and then pass that around for review. Once you sign off on it then we can move the single project to github. Stay tuned...
